# Generated by Django 5.0.6 on 2026-09-16 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Show this item on the club (section-level on/off).",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Live on the public club. Toggled via the publish action.",
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
            ],
            options={
                "ordering": ["display_order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FooterConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("about_text", models.TextField(blank=True)),
                (
                    "link_columns",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"title": "About Us", "links": [{"label": "...", "url": "..."}]}]',
                    ),
                ),
                ("newsletter_enabled", models.BooleanField(default=True)),
                ("newsletter_heading", models.CharField(blank=True, max_length=200)),
                ("copyright_text", models.CharField(blank=True, max_length=200)),
                (
                    "bottom_links",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"label": "Terms", "url": "/terms"}] - legal links on the bottom bar.',
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer configuration",
            },
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=140)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("icon", "Icon"),
                            ("logo", "Logo"),
                            ("video", "Video"),
                        ],
                        default="image",
                        max_length=10,
                    ),
                ),
                ("file", models.FileField(upload_to="website/media/")),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Describes the image for SEO / screen readers.",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StatItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Show this item on the club (section-level on/off).",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Live on the public club. Toggled via the publish action.",
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("value", models.CharField(max_length=40)),
                ("label", models.CharField(max_length=120)),
            ],
            options={
                "ordering": ["display_order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BrandLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Show this item on the club (section-level on/off).",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Live on the public club. Toggled via the publish action.",
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=120)),
                ("url", models.URLField(blank=True)),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="website.mediaasset",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Show this item on the club (section-level on/off).",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Live on the public club. Toggled via the publish action.",
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("heading", models.CharField(max_length=200)),
                ("subheading", models.CharField(blank=True, max_length=300)),
                ("cta_label", models.CharField(blank=True, max_length=60)),
                ("cta_url", models.CharField(blank=True, max_length=255)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="website.mediaasset",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProcessStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Show this item on the club (section-level on/off).",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Live on the public club. Toggled via the publish action.",
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("step_no", models.CharField(blank=True, max_length=8)),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="website.mediaasset",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SEOSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "path",
                    models.CharField(
                        default="/",
                        help_text='Page path, e.g. "/" for the home page.',
                        max_length=200,
                        unique=True,
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.CharField(blank=True, max_length=400)),
                ("canonical_url", models.URLField(blank=True)),
                (
                    "robots",
                    models.CharField(blank=True, default="index,follow", max_length=60),
                ),
                (
                    "structured_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional JSON-LD object served in the page head.",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Social share image (Open Graph).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="website.mediaasset",
                    ),
                ),
            ],
            options={
                "ordering": ["path"],
            },
        ),
        migrations.CreateModel(
            name="SiteSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Show this item on the club (section-level on/off).",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Live on the public club. Toggled via the publish action.",
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("hero", "Hero"),
                            ("how_it_works", "How It Works"),
                            ("why_choose_us", "Why Choose Us"),
                            ("services", "Services"),
                            ("packages", "Packages"),
                            ("membership", "Membership Highlights"),
                            ("projects", "Latest Projects"),
                            ("stats", "Stats"),
                            ("brands", "Trusted Brands"),
                            ("testimonials", "Testimonials"),
                            ("faq", "FAQ"),
                            ("cta_band", "Call To Action"),
                            ("app_promo", "App Promo"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "eyebrow",
                    models.CharField(
                        blank=True,
                        help_text="Small label above the title.",
                        max_length=120,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                ("primary_button_label", models.CharField(blank=True, max_length=60)),
                ("primary_button_url", models.CharField(blank=True, max_length=255)),
                ("secondary_button_label", models.CharField(blank=True, max_length=60)),
                ("secondary_button_url", models.CharField(blank=True, max_length=255)),
                (
                    "animation",
                    models.CharField(
                        blank=True,
                        help_text="Optional animation hint, e.g. fade / slide.",
                        max_length=60,
                    ),
                ),
                (
                    "background_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="website.mediaasset",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="website.mediaasset",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Show this item on the club (section-level on/off).",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Live on the public club. Toggled via the publish action.",
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("author_name", models.CharField(max_length=120)),
                ("author_role", models.CharField(blank=True, max_length=120)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(default=5, help_text="1–5 stars."),
                ),
                ("quote", models.TextField()),
                (
                    "author_photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="website.mediaasset",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WhyChooseUsPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Show this item on the club (section-level on/off).",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Live on the public club. Toggled via the publish action.",
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="website.mediaasset",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
                "abstract": False,
            },
        ),
    ]
