# Generated by Django 5.0.6 on 2026-09-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesection",
            name="key",
            field=models.CharField(
                choices=[
                    ("hero", "Hero"),
                    ("how_it_works", "How It Works"),
                    ("why_choose_us", "Why Choose Us"),
                    ("services", "Services"),
                    ("clubs", "Clubs & Venues"),
                    ("availability", "Live Availability"),
                    ("owner_cta", "For Club Owners"),
                    ("packages", "Packages"),
                    ("membership", "Membership Highlights"),
                    ("projects", "Latest Projects"),
                    ("stats", "Stats"),
                    ("brands", "Trusted Brands"),
                    ("testimonials", "Testimonials"),
                    ("faq", "FAQ"),
                    ("cta_band", "Call To Action"),
                    ("app_promo", "App Promo"),
                ],
                max_length=32,
                unique=True,
            ),
        ),
    ]
