# Generated by Django 5.0.6 on 2026-09-17 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0002_club_buffer_after_minutes_club_buffer_before_minutes_and_more"),
        (
            "facilities",
            "0004_facility_booking_hours_facility_buffer_after_minutes_and_more",
        ),
        ("promotions", "0001_initial"),
        ("settings_app", "0006_seed_theme_presets"),
        ("website", "0002_alter_sitesection_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Show this item on the club (section-level on/off).",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Live on the public club. Toggled via the publish action.",
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name, e.g. Ramadan 2027 offer.",
                        max_length=140,
                    ),
                ),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("offer", "Offer / Promotion"),
                            ("holiday", "Holiday Greeting"),
                            ("ramadan", "Ramadan"),
                            ("eid", "Eid"),
                            ("national_day", "National Day"),
                            ("event", "Event"),
                            ("tournament", "Tournament"),
                            ("membership", "Membership Offer"),
                            ("new_facility", "New Facility"),
                            ("announcement", "Announcement"),
                            ("maintenance", "Maintenance Notice"),
                            ("marketing", "General Marketing"),
                            ("custom", "Custom"),
                        ],
                        default="offer",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Headline shown to the customer.",
                        max_length=160,
                    ),
                ),
                ("subtitle", models.CharField(blank=True, max_length=240)),
                ("description", models.TextField(blank=True)),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Describes the artwork for screen readers. Leave empty if decorative.",
                        max_length=200,
                    ),
                ),
                ("cta_label", models.CharField(blank=True, max_length=60)),
                (
                    "cta_url",
                    models.CharField(
                        blank=True,
                        help_text="An internal path such as /book, or a full https:// address.",
                        max_length=500,
                    ),
                ),
                ("secondary_cta_label", models.CharField(blank=True, max_length=60)),
                ("secondary_cta_url", models.CharField(blank=True, max_length=500)),
                (
                    "starts_at",
                    models.DateTimeField(help_text="When the campaign starts showing."),
                ),
                ("ends_at", models.DateTimeField(help_text="When it stops showing.")),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("every_visit", "Every visit"),
                            ("session", "Once per session"),
                            ("daily", "Once per day"),
                            ("once", "Once per browser"),
                            ("until_closed", "Every page until closed"),
                        ],
                        default="session",
                        max_length=14,
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("home", "Homepage only"),
                            ("booking", "Booking pages"),
                            ("all", "All public pages"),
                        ],
                        default="home",
                        max_length=10,
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("everyone", "Everyone"),
                            ("guests", "Guests only"),
                            ("members", "Signed-in customers"),
                        ],
                        default="everyone",
                        max_length=10,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[(10, "Low"), (20, "Normal"), (30, "High")],
                        default=20,
                        help_text="Only the highest-priority eligible campaign opens first.",
                    ),
                ),
                (
                    "dismissible",
                    models.BooleanField(
                        default=True,
                        help_text="Customers can close it. Turn off only for a notice they must read.",
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True, help_text="Never shown on the website."
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Hidden from the list but kept, along with its figures.",
                    ),
                ),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("dismissals", models.PositiveIntegerField(default=0)),
                ("cta_clicks", models.PositiveIntegerField(default=0)),
                (
                    "clubs",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave empty to show on the whole website.",
                        related_name="website_campaigns",
                        to="clubs.club",
                    ),
                ),
                (
                    "facilities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="website_campaigns",
                        to="facilities.facility",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Main artwork. Used on every screen unless a mobile version is set.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="website.mediaasset",
                    ),
                ),
                (
                    "mobile_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional portrait artwork for phones. Falls back to the main image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="website.mediaasset",
                    ),
                ),
                (
                    "promo_code",
                    models.ForeignKey(
                        blank=True,
                        help_text="Promotes this code. Validation stays with the promo engine.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="website_campaigns",
                        to="promotions.promocode",
                    ),
                ),
                (
                    "schedule_exception",
                    models.ForeignKey(
                        blank=True,
                        help_text="Borrows a special date's period. Changes nothing about the schedule.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="website_campaigns",
                        to="settings_app.scheduleexception",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "display_order", "-starts_at"],
                "indexes": [
                    models.Index(
                        fields=["starts_at", "ends_at"],
                        name="website_web_starts__6f0410_idx",
                    ),
                    models.Index(
                        fields=["is_enabled", "is_published"],
                        name="website_web_is_enab_25dbdd_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="websitecampaign",
            constraint=models.CheckConstraint(
                check=models.Q(("ends_at__gt", models.F("starts_at"))),
                name="website_campaign_ends_after_start",
            ),
        ),
    ]
