# Generated by Django 5.0.6 on 2026-09-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Human-friendly booking code, e.g. BK-2A4F9C.",
                        max_length=14,
                        unique=True,
                    ),
                ),
                ("walk_in_name", models.CharField(blank=True, max_length=120)),
                ("walk_in_phone", models.CharField(blank=True, max_length=40)),
                ("walk_in_email", models.EmailField(blank=True, max_length=254)),
                (
                    "booking_type",
                    models.CharField(
                        blank=True,
                        choices=[("walk_in", "Walk-in"), ("advance", "Advance")],
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("admin", "Admin"),
                            ("website", "Website"),
                            ("phone", "Phone"),
                            ("walk_in", "Walk-in"),
                            ("other", "Other"),
                        ],
                        default="admin",
                        max_length=12,
                    ),
                ),
                ("customer_was_new", models.BooleanField(default=False)),
                ("customer_info_updated", models.BooleanField(default=False)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("urgent", "Urgent"),
                            ("vip", "VIP"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("booked", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("assigned", "Assigned"),
                            ("arrived", "Checked in"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No-show"),
                        ],
                        db_index=True,
                        default="booked",
                        max_length=12,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("scheduled_time", models.TimeField()),
                ("duration_minutes", models.PositiveSmallIntegerField(default=60)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "base_amount",
                    models.DecimalField(decimal_places=3, default=0, max_digits=11),
                ),
                (
                    "addons_amount",
                    models.DecimalField(decimal_places=3, default=0, max_digits=11),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=3, default=0, max_digits=11),
                ),
                (
                    "surcharge_amount",
                    models.DecimalField(decimal_places=3, default=0, max_digits=11),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=3, default=0, max_digits=11),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=3, default=0, max_digits=11),
                ),
                (
                    "total_raw",
                    models.DecimalField(decimal_places=6, default=0, max_digits=16),
                ),
                (
                    "total_extended",
                    models.DecimalField(decimal_places=6, default=0, max_digits=16),
                ),
                (
                    "rounding_difference",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                ("calculated_at", models.DateTimeField(blank=True, null=True)),
                ("applied_rules", models.JSONField(blank=True, default=list)),
                (
                    "promo_discount",
                    models.DecimalField(decimal_places=3, default=0, max_digits=11),
                ),
                (
                    "loyalty_discount",
                    models.DecimalField(decimal_places=3, default=0, max_digits=11),
                ),
                ("loyalty_points_redeemed", models.PositiveIntegerField(default=0)),
                ("loyalty_points_earned", models.PositiveIntegerField(default=0)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("partially_paid", "Partially paid"),
                            ("covered", "Covered by membership"),
                            ("no_payment_required", "No payment required"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("online", "Online"),
                            ("bank_transfer", "Bank transfer"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "coverage_snapshot",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                ("subscription_opt_out", models.BooleanField(default=False)),
                (
                    "recurrence",
                    models.CharField(
                        choices=[
                            ("none", "One-off"),
                            ("weekly", "Weekly"),
                            ("fortnightly", "Fortnightly"),
                        ],
                        default="none",
                        max_length=12,
                    ),
                ),
                ("customer_notes", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                ("special_instructions", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-scheduled_date", "-scheduled_time"),
            },
        ),
        migrations.CreateModel(
            name="BookingStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("booked", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("assigned", "Assigned"),
                            ("arrived", "Checked in"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No-show"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("booked", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("assigned", "Assigned"),
                            ("arrived", "Checked in"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No-show"),
                        ],
                        max_length=12,
                    ),
                ),
                ("event", models.CharField(blank=True, max_length=40)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
    ]
