# Generated by Django 5.0.6 on 2026-09-16 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("clubs", "0001_initial"),
        ("customers", "0001_initial"),
        ("facilities", "0001_initial"),
        ("promotions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="add_ons",
            field=models.ManyToManyField(
                blank=True, related_name="bookings", to="facilities.addon"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="clubs.club",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="facilities.facility",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="facility_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="facilities.facilitycategory",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="facility_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="facilities.facilitytype",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="parent_booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recurrences",
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="promo_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="promotions.promocode",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bookingstatushistory",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="bookingstatushistory",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking_transitions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["scheduled_date", "club"], name="bookings_bo_schedul_e71b2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["status", "scheduled_date"],
                name="bookings_bo_status_b26418_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["customer", "-created_at"],
                name="bookings_bo_custome_10bd54_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["assigned_to", "scheduled_date"],
                name="bookings_bo_assigne_48001e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["club", "scheduled_date"], name="bookings_bo_club_id_5a85e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingstatushistory",
            index=models.Index(
                fields=["booking", "created_at"], name="bookings_bo_booking_1d3d6a_idx"
            ),
        ),
    ]
