# Generated by Django 5.0.6 on 2026-09-16 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
        ("clubs", "0001_initial"),
        ("customers", "0001_initial"),
        ("facilities", "0003_facility_facility_types_maintenanceblock"),
        ("promotions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="end_time",
            field=models.TimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["facility", "scheduled_date", "scheduled_time"],
                name="bookings_bo_facilit_c25030_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["booked", "confirmed", "assigned", "arrived", "in_progress"],
                    )
                ),
                fields=("facility", "scheduled_date", "scheduled_time"),
                name="unique_live_booking_per_facility_slot",
            ),
        ),
    ]
