# Generated by Django 5.0.6 on 2026-09-16 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_backfill_end_time"),
        ("clubs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="The organization-wide policy. Exactly one row may set this.",
                    ),
                ),
                (
                    "min_lead_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Minimum notice before the slot starts. 0 = up to the moment it begins.",
                    ),
                ),
                (
                    "max_advance_days",
                    models.PositiveSmallIntegerField(
                        default=90,
                        help_text="How far ahead a slot may be booked. 0 = no limit.",
                    ),
                ),
                (
                    "max_active_bookings_per_customer",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Upcoming bookings one customer may hold at once. 0 = no limit.",
                    ),
                ),
                (
                    "max_bookings_per_customer_per_day",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Bookings one customer may hold on a single day. 0 = no limit.",
                    ),
                ),
                (
                    "cancellation_cutoff_hours",
                    models.PositiveSmallIntegerField(
                        default=24,
                        help_text="A customer may cancel until this many hours before the slot. 0 = right up to the start. Staff are never blocked.",
                    ),
                ),
                (
                    "enforce_for_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Apply the booking limits to admin-created bookings too.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.OneToOneField(
                        blank=True,
                        help_text="Leave empty for the organization-wide default.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_policy",
                        to="clubs.club",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "booking policies",
                "ordering": ("-is_default", "club"),
            },
        ),
        migrations.AddConstraint(
            model_name="bookingpolicy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="unique_default_booking_policy",
            ),
        ),
    ]
