# Generated by Django 5.0.6 on 2026-09-16 16:18

import apps.settings_app.currency
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_bookingpolicy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="currency",
            field=models.CharField(
                default=apps.settings_app.currency.get_default_currency, max_length=3
            ),
        ),
    ]
