# Generated by Django 5.0.6 on 2026-09-17 12:32

import apps.settings_app.currency
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_alter_booking_currency"),
        ("clubs", "0002_club_buffer_after_minutes_club_buffer_before_minutes_and_more"),
        ("customers", "0001_initial"),
        (
            "facilities",
            "0004_facility_booking_hours_facility_buffer_after_minutes_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingpolicy",
            name="allow_multiple_dates",
            field=models.BooleanField(
                blank=True,
                help_text="Let those slots fall on different dates. Empty inherits.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bookingpolicy",
            name="allow_multiple_slots",
            field=models.BooleanField(
                blank=True,
                help_text="Let a customer put several time slots in one booking. Empty inherits.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bookingpolicy",
            name="facility",
            field=models.OneToOneField(
                blank=True,
                help_text="A policy for one physical unit. Leave empty for a club or organization policy.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_policy",
                to="facilities.facility",
            ),
        ),
        migrations.AddField(
            model_name="bookingpolicy",
            name="max_slots_per_booking",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Most slots one booking may contain. Empty inherits.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bookingpolicy",
            name="min_slots_per_booking",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Fewest slots a multi-slot booking may contain. Empty inherits.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bookingpolicy",
            name="require_consecutive_slots",
            field=models.BooleanField(
                blank=True,
                help_text="Selected slots must run back to back. Empty inherits.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="BookingOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        db_index=True, editable=False, max_length=14, unique=True
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default=apps.settings_app.currency.get_default_currency,
                        max_length=3,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("website", "Website"),
                            ("phone", "Phone"),
                            ("walk_in", "Walk-in"),
                            ("other", "Other"),
                        ],
                        default="website",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking_orders",
                        to="clubs.club",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_booking_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking_orders",
                        to="customers.customer",
                    ),
                ),
                (
                    "facility_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking_orders",
                        to="facilities.facilitytype",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="bookings.bookingorder",
            ),
        ),
        migrations.AddIndex(
            model_name="bookingorder",
            index=models.Index(
                fields=["customer", "-created_at"],
                name="bookings_bo_custome_9f7bd1_idx",
            ),
        ),
    ]
