# Generated by Django 5.0.6 on 2026-09-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_bookingpolicy_allow_multiple_dates_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="period_type",
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
    ]
