# Generated by Django 5.0.6 on 2026-09-17 21:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_booking_period_type"),
        ("clubs", "0002_club_buffer_after_minutes_club_buffer_before_minutes_and_more"),
        ("customers", "0001_initial"),
        ("facilities", "0005_pricingrule_period_types"),
        ("promotions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="booking",
            name="unique_live_booking_per_facility_slot",
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "booked",
                            "confirmed",
                            "assigned",
                            "arrived",
                            "in_progress",
                            "completed",
                            "closed",
                        ],
                    )
                ),
                fields=("facility", "scheduled_date", "scheduled_time"),
                name="unique_live_booking_per_facility_slot",
            ),
        ),
    ]
