# Generated by Django 5.0.6 on 2026-09-18 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookings",
            "0009_remove_booking_unique_live_booking_per_facility_slot_and_more",
        ),
        ("clubs", "0003_club_cash_enabled_club_hold_max_minutes_and_more"),
        ("customers", "0001_initial"),
        ("facilities", "0005_pricingrule_period_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingHold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Human-friendly reservation code, e.g. HLD-2A4F9C.",
                        max_length=14,
                        unique=True,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("website", "Website"),
                            ("phone", "Phone"),
                            ("walk_in", "Walk-in"),
                            ("other", "Other"),
                        ],
                        default="website",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("converted", "Converted"),
                            ("released", "Released"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=12,
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("max_expires_at", models.DateTimeField()),
                ("extended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="holds",
                        to="bookings.booking",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_holds",
                        to="clubs.club",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_booking_holds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_holds",
                        to="customers.customer",
                    ),
                ),
                (
                    "facility_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_holds",
                        to="facilities.facilitytype",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="holds",
                        to="bookings.bookingorder",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="BookingHoldSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_date", models.DateField(db_index=True)),
                ("scheduled_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="held_slots",
                        to="facilities.facility",
                    ),
                ),
                (
                    "hold",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="bookings.bookinghold",
                    ),
                ),
            ],
            options={
                "ordering": ("scheduled_date", "scheduled_time"),
            },
        ),
        migrations.AddIndex(
            model_name="bookinghold",
            index=models.Index(
                fields=["status", "expires_at"], name="bookings_bo_status_d6fde9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bookinghold",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("booking__isnull", True), ("order__isnull", True), _connector="OR"
                ),
                name="hold_converts_to_one_of_booking_or_order",
            ),
        ),
        migrations.AddIndex(
            model_name="bookingholdslot",
            index=models.Index(
                fields=["scheduled_date", "facility"],
                name="bookings_bo_schedul_c00333_idx",
            ),
        ),
    ]
