# Generated by Django 5.0.6 on 2026-09-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0010_bookinghold_bookingholdslot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("booked", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("assigned", "Assigned"),
                    ("arrived", "Checked in"),
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                    ("closed", "Closed"),
                    ("cancelled", "Cancelled"),
                    ("no_show", "No-show"),
                ],
                db_index=True,
                default="booked",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="bookingstatushistory",
            name="from_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("draft", "Draft"),
                    ("booked", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("assigned", "Assigned"),
                    ("arrived", "Checked in"),
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                    ("closed", "Closed"),
                    ("cancelled", "Cancelled"),
                    ("no_show", "No-show"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="bookingstatushistory",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("booked", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("assigned", "Assigned"),
                    ("arrived", "Checked in"),
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                    ("closed", "Closed"),
                    ("cancelled", "Cancelled"),
                    ("no_show", "No-show"),
                ],
                max_length=12,
            ),
        ),
    ]
