# Generated by Django 5.0.6 on 2026-09-16 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clubs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'Court 1', 'Lane 3', 'Hall A'.", max_length=40
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilities",
                        to="clubs.club",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "facilities",
                "ordering": ("club", "name"),
            },
        ),
        migrations.CreateModel(
            name="FacilityCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("outdoor_court", "Outdoor Court"),
                            ("indoor_court", "Indoor Court"),
                            ("pitch", "Pitch / Field"),
                            ("aquatic", "Aquatic"),
                            ("hall", "Hall"),
                            ("meeting_room", "Meeting Room"),
                            ("other", "Other"),
                        ],
                        default="outdoor_court",
                        max_length=15,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Short description."),
                ),
                ("base_duration_minutes", models.PositiveSmallIntegerField(default=60)),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Default price for a booking made against the category itself (high-precision; line amounts round to the currency's precision).",
                        max_digits=12,
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="facility_categories/banners/"
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        help_text="Optional, for admin / compact list views.",
                        null=True,
                        upload_to="facility_categories/icons/",
                    ),
                ),
                (
                    "badge_label",
                    models.CharField(
                        blank=True,
                        help_text="e.g. NEW, POPULAR, PREMIUM.",
                        max_length=30,
                    ),
                ),
                (
                    "badge_status",
                    models.CharField(
                        choices=[("show", "Show"), ("hide", "Hide")],
                        default="hide",
                        max_length=4,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("meta_title", models.CharField(blank=True, max_length=160)),
                ("meta_description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "available_clubs",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Clubs this category is available at.",
                        related_name="facility_categories",
                        to="clubs.club",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "facility categories",
                "ordering": ("display_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="AddOn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Optional unique code / SKU.",
                        max_length=40,
                        null=True,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                (
                    "tax_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_inclusive",
                    models.BooleanField(
                        default=False,
                        help_text="On = the price already includes tax; off = tax is added on top.",
                    ),
                ),
                ("duration_minutes", models.PositiveSmallIntegerField(default=0)),
                ("available_all_clubs", models.BooleanField(default=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="addons/icons/"),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "available_clubs",
                    models.ManyToManyField(
                        blank=True, related_name="addons", to="clubs.club"
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Optional facility categories this add-on belongs to.",
                        related_name="addons",
                        to="facilities.facilitycategory",
                    ),
                ),
            ],
            options={
                "ordering": ("display_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="FacilityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="Short subtitle shown next to the name, e.g. 'Floodlit, all-weather'.",
                        max_length=120,
                    ),
                ),
                (
                    "badge",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("premium", "Premium"),
                            ("recommended", "Recommended"),
                            ("bestseller", "Bestseller"),
                        ],
                        default="",
                        help_text="Highlight pill: Premium / Recommended / Bestseller.",
                        max_length=12,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("whats_included", models.TextField(blank=True)),
                ("whats_not_included", models.TextField(blank=True)),
                ("duration_minutes", models.PositiveSmallIntegerField(default=60)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="facility_types/images/"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="facility_types/videos/"
                    ),
                ),
                (
                    "available_all_clubs",
                    models.BooleanField(
                        default=True,
                        help_text="If on, this facility type is bookable at every club.",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Price for one booking slot (high-precision unit price).",
                        max_digits=12,
                    ),
                ),
                (
                    "tax_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tax / VAT applied on top of the price.",
                        max_digits=5,
                    ),
                ),
                (
                    "tax_inclusive",
                    models.BooleanField(
                        default=False,
                        help_text="On = the price already includes tax; off = tax is added on top.",
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("staff_required", models.BooleanField(default=False)),
                (
                    "facility_required",
                    models.BooleanField(
                        default=True,
                        help_text="On = a booking must occupy a physical facility (court, lane, room).",
                    ),
                ),
                ("online_booking_enabled", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "add_ons",
                    models.ManyToManyField(
                        blank=True, related_name="facility_types", to="facilities.addon"
                    ),
                ),
                (
                    "available_clubs",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Clubs this facility type is bookable at (when not 'all clubs').",
                        related_name="facility_types",
                        to="clubs.club",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        help_text="The categories this facility type belongs to.",
                        related_name="facility_types",
                        to="facilities.facilitycategory",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="PricingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(max_length=40, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Lower number = higher priority when several rules match.",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("club", "Club Pricing"),
                            ("membership", "Membership Discount"),
                            ("promo", "Promo Pricing"),
                            ("date_range", "Date Range Pricing"),
                            ("weekend", "Weekend Pricing"),
                            ("peak_hour", "Peak Hour Pricing"),
                            ("custom", "Custom Pricing"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            ("fixed_increase", "Fixed Amount Increase"),
                            ("fixed_discount", "Fixed Amount Discount"),
                            ("percent_increase", "Percentage Increase"),
                            ("percent_discount", "Percentage Discount"),
                            ("override", "Override Price"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "adjustment_value",
                    models.DecimalField(decimal_places=3, default=0, max_digits=11),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, help_text="Blank = system default.", max_length=3
                    ),
                ),
                ("tax_applicable", models.BooleanField(default=False)),
                (
                    "allow_stacking",
                    models.BooleanField(
                        default=True,
                        help_text="If off, stop after this rule is applied.",
                    ),
                ),
                ("customer_types", models.JSONField(blank=True, default=list)),
                ("days_of_week", models.JSONField(blank=True, default=list)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "min_amount",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=11, null=True
                    ),
                ),
                ("min_quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "addons",
                    models.ManyToManyField(
                        blank=True, related_name="pricing_rules", to="facilities.addon"
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="pricing_rules",
                        to="facilities.facilitycategory",
                    ),
                ),
                (
                    "clubs",
                    models.ManyToManyField(
                        blank=True, related_name="pricing_rules", to="clubs.club"
                    ),
                ),
                (
                    "facility_types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="pricing_rules",
                        to="facilities.facilitytype",
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "display_order", "name"),
            },
        ),
    ]
