# Generated by Django 5.0.6 on 2026-09-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("facilities", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingrule",
            name="membership_plans",
            field=models.ManyToManyField(
                blank=True, related_name="pricing_rules", to="payments.membershipplan"
            ),
        ),
        migrations.AddConstraint(
            model_name="facility",
            constraint=models.UniqueConstraint(
                fields=("club", "name"), name="unique_facility_per_club"
            ),
        ),
        migrations.AddIndex(
            model_name="facilitycategory",
            index=models.Index(
                fields=["kind", "is_active"], name="facilities__kind_d6958d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="facilitytype",
            index=models.Index(
                fields=["is_active"], name="facilities__is_acti_e41644_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricingrule",
            index=models.Index(
                fields=["is_active", "rule_type"], name="facilities__is_acti_244e6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricingrule",
            index=models.Index(
                fields=["priority"], name="facilities__priorit_d6c7f1_idx"
            ),
        ),
    ]
