# Generated by Django 5.0.6 on 2026-09-16 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="facility_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Which facility types this unit can be booked as. Leave empty to make it usable for any type.",
                related_name="facilities",
                to="facilities.facilitytype",
            ),
        ),
        migrations.CreateModel(
            name="MaintenanceBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        help_text="Inclusive - the last day out of service."
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True, help_text="Blank = all day.", null=True
                    ),
                ),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Resurfacing', 'Net replacement'.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_blocks",
                        to="facilities.facility",
                    ),
                ),
            ],
            options={
                "ordering": ("-start_date", "facility"),
                "indexes": [
                    models.Index(
                        fields=["facility", "start_date", "end_date"],
                        name="facilities__facilit_49e82f_idx",
                    )
                ],
            },
        ),
    ]
