# Generated by Django 5.0.6 on 2026-09-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "facilities",
            "0004_facility_booking_hours_facility_buffer_after_minutes_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingrule",
            name="period_types",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
