# Generated by Django 5.0.6 on 2026-09-16 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clubs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=20, unique=True)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-time"),
                            ("part_time", "Part-time"),
                            ("contract", "Contract"),
                        ],
                        default="full_time",
                        max_length=12,
                    ),
                ),
                (
                    "skills",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated skill tags, e.g. 'tennis coaching, lifeguard'.",
                        max_length=255,
                    ),
                ),
                ("hired_on", models.DateField(blank=True, null=True)),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Master on/off switch for new assignments.",
                    ),
                ),
                ("shift_hours", models.JSONField(blank=True, default=dict)),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Rolling average customer rating, 0-5.",
                        max_digits=3,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "base_club",
                    models.ForeignKey(
                        blank=True,
                        help_text="Home club (from the club master).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="clubs.club",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("employee_id",),
            },
        ),
        migrations.CreateModel(
            name="StaffClubTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effective_date", models.DateField()),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate"),
                            ("scheduled", "Scheduled"),
                        ],
                        default="immediate",
                        max_length=10,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("remarks", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_approval", "Pending approval"),
                            ("approved", "Approved (scheduled)"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending_approval",
                        max_length=20,
                    ),
                ),
                (
                    "shift_option",
                    models.CharField(
                        choices=[
                            ("apply_club", "Apply destination club schedule"),
                            ("retain_custom", "Retain employee custom schedule"),
                            ("configure", "Configure new schedule later"),
                        ],
                        default="apply_club",
                        max_length=14,
                    ),
                ),
                ("reassign_plan", models.JSONField(blank=True, default=dict)),
                ("impact_snapshot", models.JSONField(blank=True, default=dict)),
                ("cancel_reason", models.CharField(blank=True, max_length=255)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="clubs.club",
                    ),
                ),
                (
                    "to_club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="clubs.club",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="staff.staffprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="staff.staffprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("date", "start_time"),
            },
        ),
        migrations.CreateModel(
            name="PerformanceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("jobs_completed", models.PositiveSmallIntegerField(default=0)),
                (
                    "avg_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                (
                    "on_time_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance",
                        to="staff.staffprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("-date",),
            },
        ),
        migrations.AddIndex(
            model_name="staffprofile",
            index=models.Index(
                fields=["is_available"], name="staff_staff_is_avai_04f569_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffclubtransfer",
            index=models.Index(
                fields=["staff", "-created_at"], name="staff_staff_staff_i_e8b207_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffclubtransfer",
            index=models.Index(
                fields=["status", "effective_date"],
                name="staff_staff_status_b74a6a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(fields=["date"], name="staff_shift_date_b48a70_idx"),
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(
                fields=["staff", "date"], name="staff_shift_staff_i_45e01a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.UniqueConstraint(
                fields=("staff", "date", "start_time"), name="unique_staff_shift_start"
            ),
        ),
        migrations.AddConstraint(
            model_name="performancesnapshot",
            constraint=models.UniqueConstraint(
                fields=("staff", "date"), name="unique_staff_perf_per_day"
            ),
        ),
    ]
