# Generated by Django 5.0.6 on 2026-09-16 14:14

import apps.settings_app.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookingConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("website_email_required", models.BooleanField(default=True)),
                ("website_phone_required", models.BooleanField(default=True)),
                ("website_email_unique", models.BooleanField(default=False)),
                ("website_phone_unique", models.BooleanField(default=False)),
                ("admin_email_required", models.BooleanField(default=False)),
                ("admin_phone_required", models.BooleanField(default=False)),
                ("admin_email_unique", models.BooleanField(default=True)),
                ("admin_phone_unique", models.BooleanField(default=True)),
                ("walkin_email_required", models.BooleanField(default=False)),
                ("walkin_phone_required", models.BooleanField(default=False)),
                ("walkin_email_unique", models.BooleanField(default=False)),
                ("walkin_phone_unique", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Booking Configuration",
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "code",
                    models.CharField(
                        help_text="ISO 4217 code, e.g. USD, AED, SAR, JPY.",
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("symbol", models.CharField(blank=True, max_length=8)),
                (
                    "precision",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="Standard transaction decimal places (JPY 0, USD 2, BHD 3).",
                    ),
                ),
                (
                    "extended_precision",
                    models.PositiveSmallIntegerField(
                        default=6,
                        help_text="Internal-calculation decimal places; must be ≥ precision.",
                    ),
                ),
                (
                    "minimum_accountable_unit",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0.01"),
                        help_text="Smallest valid currency unit final amounts snap to (e.g. 0.01).",
                        max_digits=12,
                    ),
                ),
                (
                    "rounding_method",
                    models.CharField(
                        choices=[
                            ("HALF_UP", "Half up (0.5 → away from zero)"),
                            ("HALF_EVEN", "Half even (banker's)"),
                            ("HALF_DOWN", "Half down"),
                            ("UP", "Up (away from zero)"),
                            ("DOWN", "Down (truncate)"),
                            ("CEILING", "Ceiling"),
                            ("FLOOR", "Floor"),
                        ],
                        default="HALF_UP",
                        max_length=12,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "currencies",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("legal_name", models.CharField(blank=True, max_length=200)),
                (
                    "trn",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        verbose_name="Tax Registration Number (TRN)",
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("address", models.CharField(blank=True, max_length=300)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("timezone", models.CharField(default="Asia/Dubai", max_length=64)),
                ("time_format_24h", models.BooleanField(default=False)),
                ("slot_minutes", models.PositiveSmallIntegerField(default=60)),
                (
                    "booking_hours",
                    models.JSONField(
                        blank=True,
                        default=apps.settings_app.models.default_booking_hours,
                    ),
                ),
                ("require_refund_approval", models.BooleanField(default=True)),
                ("allow_multiple_memberships", models.BooleanField(default=False)),
                (
                    "logo_light",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                (
                    "logo_dark",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                (
                    "logo_light_vertical",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                (
                    "logo_dark_vertical",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                (
                    "og_image",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.CharField(blank=True, max_length=400)),
                ("summary", models.CharField(blank=True, max_length=140)),
                ("description", models.TextField(blank=True)),
                ("facebook", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("twitter", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                ("youtube", models.URLField(blank=True)),
                ("tiktok", models.URLField(blank=True)),
                ("whatsapp", models.CharField(blank=True, max_length=40)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organization",
            },
        ),
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=60, unique=True)),
                ("value", models.JSONField(blank=True, default=dict)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("key",),
            },
        ),
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Fraction, e.g. 0.0500 for 5% VAT.",
                        max_digits=5,
                    ),
                ),
                ("country", models.CharField(default="UAE", max_length=60)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-is_default", "name"),
            },
        ),
    ]
