# Generated by Django 5.0.6 on 2026-09-16 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0002_club_buffer_after_minutes_club_buffer_before_minutes_and_more"),
        (
            "facilities",
            "0004_facility_booking_hours_facility_buffer_after_minutes_and_more",
        ),
        ("settings_app", "0002_seed_currencies"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="buffer_after_minutes",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Changeover time held after each booking."
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="buffer_before_minutes",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Preparation time held before each booking."
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="slot_minutes",
            field=models.PositiveSmallIntegerField(
                default=60, help_text="How often a bookable slot starts, in minutes."
            ),
        ),
        migrations.CreateModel(
            name="ScheduleException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Shown to staff, e.g. 'National Day'.", max_length=120
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Leave empty for a single day.", null=True
                    ),
                ),
                (
                    "closed",
                    models.BooleanField(
                        default=True,
                        help_text="Closed all day. Untick to set custom hours instead.",
                    ),
                ),
                ("shifts", models.JSONField(blank=True, default=list)),
                ("breaks", models.JSONField(blank=True, default=list)),
                (
                    "slot_minutes",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Leave empty to keep the usual slot interval.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty to apply to the whole organization.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_exceptions",
                        to="clubs.club",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule_exceptions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty to apply to the whole club.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_exceptions",
                        to="facilities.facility",
                    ),
                ),
            ],
            options={
                "ordering": ("start_date", "name"),
                "indexes": [
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="settings_ap_start_d_38ab24_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="scheduleexception",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("end_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="schedule_exception_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleexception",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("facility__isnull", True), ("club__isnull", True), _connector="OR"
                ),
                name="schedule_exception_single_scope",
            ),
        ),
    ]
