# Generated by Django 5.0.6 on 2026-09-16 18:35

from django.db import migrations, models


def seed_languages(apps, schema_editor):
    """English enabled and default, Arabic available but off.

    The application must never start with no usable language, so the default
    exists from the first migration rather than waiting for someone to create
    it. Arabic ships disabled: the direction handling is in place, and an
    administrator turns it on when the translations are ready.
    """
    Language = apps.get_model("settings_app", "Language")
    if Language.objects.exists():
        return
    Language.objects.create(
        code="en", locale="en", name="English", native_name="English",
        direction="ltr", is_enabled=True, is_default=True, display_order=1)
    Language.objects.create(
        code="ar", locale="ar", name="Arabic", native_name="العربية",
        direction="rtl", is_enabled=False, is_default=False, display_order=2)


def unseed_languages(apps, schema_editor):
    Language = apps.get_model("settings_app", "Language")
    Language.objects.filter(code__in=["en", "ar"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0003_organization_buffer_after_minutes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="IETF language tag, e.g. 'en', 'ar', 'fr'.",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        blank=True,
                        help_text="Region-specific locale for formatting, e.g. 'en-GB', 'ar-SA'. Leave empty to use the language code.",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="English name, e.g. 'Arabic'.", max_length=60
                    ),
                ),
                (
                    "native_name",
                    models.CharField(
                        help_text="The language's own name, e.g. 'العربية'.",
                        max_length=60,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("ltr", "Left to right"), ("rtl", "Right to left")],
                        default="ltr",
                        max_length=3,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Offered to users in the language selector.",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Used when a user has expressed no preference.",
                    ),
                ),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("display_order", "name"),
            },
        ),
        migrations.AddConstraint(
            model_name="language",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="unique_default_language",
            ),
        ),
            migrations.RunPython(seed_languages, unseed_languages),
    ]
