# Generated by Django 5.0.6 on 2026-09-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0004_language_language_unique_default_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThemePreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("tokens", models.JSONField(blank=True, default=dict)),
                ("is_builtin", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("display_order", "name"),
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="theme",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="organization",
            name="theme_preset_name",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
