# Generated by Django 5.0.6 on 2026-09-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0007_seed_courtside_light_preset"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="cash_enabled",
            field=models.BooleanField(
                default=True, help_text="Offer paying at the venue in cash."
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="hold_max_minutes",
            field=models.PositiveSmallIntegerField(
                default=120,
                help_text="The longest any reservation may live, in minutes, however it is extended.",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="hold_partly_paid_minutes",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="How long a part-paid reservation holds its slot, in minutes.",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="hold_unpaid_minutes",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="How long an unpaid reservation holds its slot, in minutes.",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="split_enabled",
            field=models.BooleanField(
                default=True, help_text="Offer splitting a booking between friends."
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="split_hold_minutes",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="How long a split arrangement has to collect the full amount, in minutes. Clamped to the maximum reservation lifetime: a payment link must never outlive the court it is paying for.",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="split_max_shares",
            field=models.PositiveSmallIntegerField(
                default=20, help_text="Most people one booking may be split between."
            ),
        ),
    ]
