# Generated by Django 5.0.6 on 2026-09-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0008_organization_cash_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="show_hold_countdown",
            field=models.BooleanField(
                default=True,
                help_text="Show customers how long their reservation has left.",
            ),
        ),
    ]
