# Generated by Django 5.0.6 on 2026-09-16 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                        ],
                        max_length=10,
                    ),
                ),
                ("path", models.CharField(max_length=512)),
                ("status_code", models.PositiveSmallIntegerField()),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("payload_summary", models.JSONField(blank=True, default=dict)),
                (
                    "subject_type",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                (
                    "subject_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="auditlogs_a_created_939d5f_idx"
                    ),
                    models.Index(
                        fields=["actor", "-created_at"],
                        name="auditlogs_a_actor_i_f11990_idx",
                    ),
                    models.Index(
                        fields=["subject_type", "subject_id", "-created_at"],
                        name="auditlogs_a_subject_6e820d_idx",
                    ),
                ],
            },
        ),
    ]
