# Generated by Django 5.0.6 on 2026-09-16 14:14

import apps.accounts.models
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clubs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.SlugField(max_length=40, unique=True)),
                ("name", models.CharField(blank=True, max_length=80)),
                (
                    "base_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("super_admin", "Super Admin"),
                            ("admin", "Admin"),
                            ("club_admin", "Club Admin"),
                            ("manager", "Manager"),
                            ("facility_operator", "Facility Operator"),
                            ("facility_staff", "Facility Staff"),
                            ("customer", "Customer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("permissions", models.JSONField(blank=True, default=list)),
                ("is_system", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Role access",
                "ordering": ("-is_system", "name"),
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jti", models.CharField(db_index=True, max_length=255, unique=True)),
                ("sid", models.CharField(blank=True, db_index=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("browser", models.CharField(blank=True, max_length=80)),
                ("operating_system", models.CharField(blank=True, max_length=80)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("desktop", "Desktop"),
                            ("mobile", "Mobile"),
                            ("tablet", "Tablet"),
                            ("bot", "Bot"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=10,
                    ),
                ),
                ("login_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("mfa_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("logout_reason", models.CharField(blank=True, max_length=40)),
            ],
            options={
                "ordering": ("-login_at",),
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super Admin"),
                            ("admin", "Admin"),
                            ("club_admin", "Club Admin"),
                            ("manager", "Manager"),
                            ("facility_operator", "Facility Operator"),
                            ("facility_staff", "Facility Staff"),
                            ("customer", "Customer"),
                        ],
                        db_index=True,
                        default="customer",
                        max_length=20,
                    ),
                ),
                ("role_slug", models.SlugField(blank=True, max_length=40)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("web_login_enabled", models.BooleanField(default=True)),
                ("api_login_enabled", models.BooleanField(default=True)),
                ("is_super_admin", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("failed_login_attempts", models.PositiveIntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("lock_reason", models.CharField(blank=True, max_length=120)),
                ("must_change_password", models.BooleanField(default=False)),
                (
                    "last_password_change_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("last_activity_at", models.DateTimeField(blank=True, null=True)),
                ("mfa_enabled", models.BooleanField(default=False)),
                ("mfa_secret", models.CharField(blank=True, max_length=64)),
                ("mfa_enforced", models.BooleanField(default=False)),
                ("mfa_disabled", models.BooleanField(default=True)),
                ("tokens_revoked_at", models.DateTimeField(blank=True, null=True)),
                ("permission_overrides", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_clubs",
                    models.ManyToManyField(
                        blank=True, related_name="assigned_users", to="clubs.club"
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", apps.accounts.models.UserManager()),
            ],
        ),
    ]
