# Generated by Django 5.0.6 on 2026-09-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                blank=True,
                default="",
                help_text="IETF language tag, e.g. 'en' or 'ar'. Blank follows the organization default.",
                max_length=10,
            ),
        ),
    ]
