# Generated by Django 5.0.6 on 2026-09-16 14:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoyaltyConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earning_enabled", models.BooleanField(default=False)),
                (
                    "earn_trigger",
                    models.CharField(
                        choices=[
                            ("completion", "On completion"),
                            ("payment", "On payment"),
                        ],
                        default="completion",
                        max_length=12,
                    ),
                ),
                (
                    "points_per_currency",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("1"), max_digits=8
                    ),
                ),
                ("fixed_points_per_booking", models.PositiveIntegerField(default=0)),
                ("service_bonuses", models.JSONField(blank=True, default=dict)),
                ("package_bonuses", models.JSONField(blank=True, default=dict)),
                ("membership_bonuses", models.JSONField(blank=True, default=dict)),
                ("redemption_enabled", models.BooleanField(default=False)),
                (
                    "currency_per_point",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=8
                    ),
                ),
                ("min_redeem_points", models.PositiveIntegerField(default=0)),
                (
                    "max_redeem_points_per_booking",
                    models.PositiveIntegerField(default=0),
                ),
                ("max_redeem_percent", models.PositiveIntegerField(default=0)),
                ("stack_with_promo", models.BooleanField(default=True)),
                ("stack_with_membership", models.BooleanField(default=True)),
                ("expiry_months", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Loyalty Configuration",
            },
        ),
        migrations.CreateModel(
            name="LoyaltyTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("slug", models.SlugField(max_length=40, unique=True)),
                (
                    "rank",
                    models.PositiveIntegerField(
                        default=0, help_text="Order, low = entry tier."
                    ),
                ),
                ("min_points", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "min_spend",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=13, null=True
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                ("priority_booking", models.BooleanField(default=False)),
                ("benefits", models.TextField(blank=True)),
                ("color", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("rank",),
            },
        ),
    ]
