# Generated by Django 5.0.6 on 2026-09-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="buffer_after_minutes",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Changeover time held after each booking. Empty inherits the organization.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="buffer_before_minutes",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Preparation time held before each booking. Empty inherits the organization.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="booking_hours",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Weekday overrides. Empty inherits the organization.",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="slot_minutes",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="How often a slot starts, in minutes. Empty inherits the organization.",
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="ClubHours",
        ),
    ]
