# Generated by Django 5.0.6 on 2026-09-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0002_club_buffer_after_minutes_club_buffer_before_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="cash_enabled",
            field=models.BooleanField(
                blank=True,
                help_text="Offer paying at the venue. Empty inherits the organization.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="hold_max_minutes",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Longest any reservation may live, in minutes. Empty inherits the organization.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="hold_partly_paid_minutes",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Part-paid reservation hold, in minutes. Empty inherits the organization.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="hold_unpaid_minutes",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Unpaid reservation hold, in minutes. Empty inherits the organization.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="split_enabled",
            field=models.BooleanField(
                blank=True,
                help_text="Offer split payment. Empty inherits the organization.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="split_hold_minutes",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Split collection window, in minutes. Empty inherits the organization.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="split_max_shares",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Most people a booking may be split between. Empty inherits the organization.",
                null=True,
            ),
        ),
    ]
