# Generated by Django 5.0.6 on 2026-09-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0003_club_cash_enabled_club_hold_max_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="show_hold_countdown",
            field=models.BooleanField(
                blank=True,
                help_text="Show the reservation countdown. Empty inherits the organization.",
                null=True,
            ),
        ),
    ]
