# Generated by Django 5.0.6 on 2026-09-16 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login_invited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer_code",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("corporate", "Corporate"),
                            ("fleet", "Fleet"),
                        ],
                        default="individual",
                        max_length=12,
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=160)),
                ("mobile_number", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("whatsapp_number", models.CharField(blank=True, max_length=20)),
                ("gender", models.CharField(blank=True, max_length=10)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("nationality", models.CharField(blank=True, max_length=80)),
                ("preferred_language", models.CharField(blank=True, max_length=20)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("area", models.CharField(blank=True, max_length=100)),
                (
                    "trn",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        verbose_name="Tax Registration Number (TRN)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("is_vip", models.BooleanField(default=False)),
                ("is_member", models.BooleanField(default=False)),
                ("is_group", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_method", models.CharField(blank=True, max_length=24)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("web", "Website"),
                            ("admin", "Admin"),
                            ("walk_in", "Walk-in"),
                            ("referral", "Referral"),
                            ("other", "Other"),
                        ],
                        default="web",
                        max_length=20,
                    ),
                ),
                ("loyalty_points", models.PositiveIntegerField(default=0)),
                (
                    "loyalty_tier",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                            ("platinum", "Platinum"),
                        ],
                        default="bronze",
                        max_length=10,
                    ),
                ),
                ("loyalty_points_earned", models.PositiveIntegerField(default=0)),
                ("loyalty_points_redeemed", models.PositiveIntegerField(default=0)),
                ("loyalty_points_expired", models.PositiveIntegerField(default=0)),
                (
                    "loyalty_spend",
                    models.DecimalField(decimal_places=3, default=0, max_digits=13),
                ),
                ("tier_since", models.DateField(blank=True, null=True)),
                (
                    "lifetime_value",
                    models.DecimalField(decimal_places=3, default=0, max_digits=13),
                ),
                ("member_since", models.DateField(auto_now_add=True)),
                (
                    "is_corporate",
                    models.BooleanField(
                        default=False,
                        help_text="Fleet / corporate account with PO billing.",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("office", "Office"),
                            ("parking", "Parking"),
                            ("other", "Other"),
                        ],
                        default="home",
                        max_length=20,
                    ),
                ),
                ("line1", models.CharField(max_length=255)),
                ("line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(default="UAE", max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("parking_bay", models.CharField(blank=True, max_length=50)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_saved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ("-is_default", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="LoyaltyLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "txn_type",
                    models.CharField(
                        choices=[
                            ("earn", "Earned"),
                            ("redeem", "Redeemed"),
                            ("expire", "Expired"),
                            ("adjust", "Adjusted"),
                            ("reversed", "Reversed"),
                            ("merged", "Merged"),
                            ("bonus", "Bonus"),
                            ("correction", "Correction"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        help_text="Positive for earn/adjust+/bonus, negative for redeem/expire/reverse."
                    ),
                ),
                ("balance_before", models.IntegerField(default=0)),
                ("balance_after", models.IntegerField(default=0)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("admin", "Admin"),
                            ("booking", "Booking"),
                            ("invoice", "Invoice"),
                            ("merge", "Merge"),
                            ("seed", "Seed"),
                            ("website", "Website"),
                        ],
                        default="system",
                        max_length=12,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "related_booking_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("related_invoice_ref", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_entries",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["loyalty_tier"], name="customers_c_loyalty_5162a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["is_corporate"], name="customers_c_is_corp_f63a3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loyaltyledger",
            index=models.Index(
                fields=["customer", "-created_at"],
                name="customers_l_custome_3c2747_idx",
            ),
        ),
    ]
