# Generated by Django 5.0.6 on 2026-09-16 14:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("clubs", "0001_initial"),
        ("customers", "0001_initial"),
        ("facilities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "code",
                    models.CharField(blank=True, max_length=40, null=True, unique=True),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("half_yearly", "Half-yearly"),
                            ("annual", "Yearly"),
                            ("custom", "Custom duration"),
                        ],
                        default="monthly",
                        max_length=12,
                    ),
                ),
                (
                    "validity_mode",
                    models.CharField(
                        choices=[
                            ("rolling", "Rolling from purchase date"),
                            ("fixed", "Fixed start & end date"),
                        ],
                        default="rolling",
                        max_length=8,
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("fixed_start", models.DateField(blank=True, null=True)),
                ("fixed_end", models.DateField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=3, max_digits=9)),
                ("eligible_tiers", models.JSONField(blank=True, default=list)),
                (
                    "is_group",
                    models.BooleanField(
                        default=False,
                        help_text="Family / group plan shared by several members.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "available_clubs",
                    models.ManyToManyField(
                        blank=True, related_name="membership_plans", to="clubs.club"
                    ),
                ),
            ],
            options={
                "ordering": ("price",),
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("auto_renew", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memberships",
                        to="clubs.club",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="customers.customer",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="payments.membershipplan",
                    ),
                ),
            ],
            options={
                "ordering": ("-start_date",),
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        db_index=True, editable=False, max_length=18, unique=True
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("card", "Card"),
                            ("cash", "Cash"),
                            ("wallet", "Wallet"),
                            ("membership", "Membership"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("amount", models.DecimalField(decimal_places=3, max_digits=13)),
                (
                    "refunded_amount",
                    models.DecimalField(decimal_places=3, default=0, max_digits=13),
                ),
                ("gateway", models.CharField(default="mock", max_length=40)),
                ("gateway_reference", models.CharField(blank=True, max_length=120)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="bookings.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("bill_to_name", models.CharField(blank=True, max_length=160)),
                ("bill_to_email", models.CharField(blank=True, max_length=254)),
                ("bill_to_trn", models.CharField(blank=True, max_length=30)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("subtotal", models.DecimalField(decimal_places=3, max_digits=13)),
                ("tax_amount", models.DecimalField(decimal_places=3, max_digits=13)),
                ("total", models.DecimalField(decimal_places=3, max_digits=13)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "total_raw",
                    models.DecimalField(decimal_places=6, default=0, max_digits=16),
                ),
                (
                    "total_extended",
                    models.DecimalField(decimal_places=6, default=0, max_digits=16),
                ),
                (
                    "rounding_difference",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "Issued"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                            ("partially_refunded", "Partially refunded"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="issued",
                        max_length=20,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("sale", "Sale"),
                            ("membership_purchase", "Membership purchase"),
                            ("membership_renewal", "Membership renewal"),
                        ],
                        default="sale",
                        max_length=20,
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.CharField(blank=True, max_length=255)),
                ("pdf", models.FileField(blank=True, null=True, upload_to="invoices/")),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="bookings.booking",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="customers.customer",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="payments.membership",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "ordering": ("-issued_at",),
            },
        ),
        migrations.CreateModel(
            name="PlanEntitlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("facility_type", "Facility type"),
                            ("category", "Facility category"),
                            ("addon", "Add-on"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "limit_type",
                    models.CharField(
                        choices=[("unlimited", "Unlimited"), ("limited", "Limited")],
                        default="limited",
                        max_length=10,
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("lifetime", "Per membership (lifetime)"),
                            ("monthly", "Per month"),
                            ("weekly", "Per week"),
                            ("daily", "Per day"),
                        ],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                (
                    "addon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="facilities.addon",
                    ),
                ),
                (
                    "facility_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="facilities.facilitycategory",
                    ),
                ),
                (
                    "facility_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="facilities.facilitytype",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entitlements",
                        to="payments.membershipplan",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="MembershipUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "txn_type",
                    models.CharField(
                        choices=[
                            ("reserve", "Reserve"),
                            ("release", "Release"),
                            ("consume", "Consume"),
                            ("restore", "Restore"),
                            ("adjust", "Adjust"),
                        ],
                        max_length=10,
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                ("target_label", models.CharField(blank=True, max_length=160)),
                ("period_key", models.CharField(blank=True, max_length=12)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="membership_usage",
                        to="bookings.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage",
                        to="payments.membership",
                    ),
                ),
                (
                    "entitlement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="payments.planentitlement",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="MembershipBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_key", models.CharField(blank=True, max_length=12)),
                ("consumed", models.PositiveIntegerField(default=0)),
                ("reserved", models.PositiveIntegerField(default=0)),
                ("granted", models.PositiveIntegerField(default=0)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to="payments.membership",
                    ),
                ),
                (
                    "entitlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="payments.planentitlement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("amount", models.DecimalField(decimal_places=3, max_digits=13)),
                ("method", models.CharField(blank=True, max_length=12)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("pdf", models.FileField(blank=True, null=True, upload_to="receipts/")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="customers.customer",
                    ),
                ),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt",
                        to="payments.invoice",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipts",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "ordering": ("-issued_at",),
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=18,
                        null=True,
                        unique=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=3, max_digits=13)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("method", models.CharField(blank=True, max_length=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("pending", "Pending"),
                            ("failed", "Failed"),
                        ],
                        default="completed",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_refunds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="CreditNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_approval", "Pending approval"),
                            ("issued", "Issued"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="issued",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("subtotal", models.DecimalField(decimal_places=3, max_digits=13)),
                ("tax_amount", models.DecimalField(decimal_places=3, max_digits=13)),
                ("total", models.DecimalField(decimal_places=3, max_digits=13)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "total_raw",
                    models.DecimalField(decimal_places=6, default=0, max_digits=16),
                ),
                (
                    "total_extended",
                    models.DecimalField(decimal_places=6, default=0, max_digits=16),
                ),
                (
                    "rounding_difference",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("method", models.CharField(blank=True, max_length=15)),
                (
                    "requested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, default="")),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pdf",
                    models.FileField(blank=True, null=True, upload_to="credit-notes/"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_credit_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_credit_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_notes",
                        to="customers.customer",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_credit_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_credit_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_notes",
                        to="payments.invoice",
                    ),
                ),
                (
                    "refund",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_note",
                        to="payments.refund",
                    ),
                ),
            ],
            options={
                "ordering": ("-requested_at",),
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "balance",
                    models.DecimalField(decimal_places=3, default=0, max_digits=13),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to="customers.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WalletTxn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "txn_type",
                    models.CharField(
                        choices=[
                            ("topup", "Top-up"),
                            ("charge", "Charge"),
                            ("refund", "Refund"),
                            ("adjust", "Adjustment"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Positive credits the wallet, negative debits it.",
                        max_digits=13,
                    ),
                ),
                ("balance_after", models.DecimalField(decimal_places=3, max_digits=13)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "related_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wallet_txns",
                        to="payments.payment",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="payments.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["customer", "status"], name="payments_me_custome_7f28ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["status", "end_date"], name="payments_me_status_8df0d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["customer", "-created_at"],
                name="payments_pa_custome_a935a8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "-created_at"], name="payments_pa_status_21ed42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["customer", "-issued_at"], name="payments_in_custome_9d443c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membershipusage",
            index=models.Index(
                fields=["membership", "-created_at"],
                name="payments_me_members_7cd94e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="membershipusage",
            index=models.Index(
                fields=["booking", "txn_type"], name="payments_me_booking_241047_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="membershipbalance",
            constraint=models.UniqueConstraint(
                fields=("membership", "entitlement", "period_key"),
                name="unique_membership_balance_bucket",
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["customer", "-issued_at"], name="payments_re_custome_ca8d98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creditnote",
            index=models.Index(
                fields=["customer", "-requested_at"],
                name="payments_cr_custome_3f8258_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="creditnote",
            index=models.Index(
                fields=["invoice", "status"], name="payments_cr_invoice_f98804_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wallettxn",
            index=models.Index(
                fields=["wallet", "-created_at"], name="payments_wa_wallet__65897e_idx"
            ),
        ),
    ]
