# Generated by Django 5.0.6 on 2026-09-16 16:18

import apps.settings_app.currency
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditnote",
            name="currency",
            field=models.CharField(
                default=apps.settings_app.currency.get_default_currency, max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="currency",
            field=models.CharField(
                default=apps.settings_app.currency.get_default_currency, max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                default=apps.settings_app.currency.get_default_currency, max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="currency",
            field=models.CharField(
                default=apps.settings_app.currency.get_default_currency, max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="currency",
            field=models.CharField(
                default=apps.settings_app.currency.get_default_currency, max_length=3
            ),
        ),
    ]
