# Generated by Django 5.0.6 on 2026-09-17 08:44

import apps.settings_app.currency
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_alter_booking_currency"),
        ("customers", "0001_initial"),
        ("payments", "0002_alter_creditnote_currency_alter_invoice_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="card_brand",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="payment",
            name="card_last4",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.CreateModel(
            name="BookingPaymentSplit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default=apps.settings_app.currency.get_default_currency,
                        max_length=3,
                    ),
                ),
                (
                    "amount_allocated",
                    models.DecimalField(decimal_places=3, default=0, max_digits=13),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Awaiting payment"),
                            ("completed", "Fully paid"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=12,
                    ),
                ),
                (
                    "organizer_token_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_splits",
                        to="bookings.booking",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_splits",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="BookingPaymentShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("participant_name", models.CharField(blank=True, max_length=120)),
                ("participant_email", models.EmailField(blank=True, max_length=254)),
                ("participant_phone", models.CharField(blank=True, max_length=32)),
                ("is_organizer", models.BooleanField(default=False)),
                ("amount", models.DecimalField(decimal_places=3, max_digits=13)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True, unique=True
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("last_failure_code", models.CharField(blank=True, max_length=40)),
                ("reminder_count", models.PositiveSmallIntegerField(default=0)),
                ("last_reminder_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="split_share",
                        to="payments.payment",
                    ),
                ),
                (
                    "split",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="payments.bookingpaymentsplit",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="bookingpaymentsplit",
            index=models.Index(
                fields=["status", "expires_at"], name="payments_bo_status_07173f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingpaymentsplit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("booking",),
                name="unique_active_split_per_booking",
            ),
        ),
        migrations.AddIndex(
            model_name="bookingpaymentshare",
            index=models.Index(
                fields=["split", "status"], name="payments_bo_split_i_ad6936_idx"
            ),
        ),
    ]
