# Generated by Django 5.0.6 on 2026-09-17 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_bookingpolicy_allow_multiple_dates_and_more"),
        ("customers", "0001_initial"),
        ("payments", "0003_payment_card_brand_payment_card_last4_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bookingpaymentsplit",
            name="unique_active_split_per_booking",
        ),
        migrations.AddField(
            model_name="bookingpaymentsplit",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_splits",
                to="bookings.bookingorder",
            ),
        ),
        migrations.AlterField(
            model_name="bookingpaymentsplit",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_splits",
                to="bookings.booking",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingpaymentsplit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("booking__isnull", False), ("status", "active")),
                fields=("booking",),
                name="unique_active_split_per_booking",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingpaymentsplit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("order__isnull", False), ("status", "active")),
                fields=("order",),
                name="unique_active_split_per_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingpaymentsplit",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("booking__isnull", False), ("order__isnull", True)),
                    models.Q(("booking__isnull", True), ("order__isnull", False)),
                    _connector="OR",
                ),
                name="split_targets_one_of_booking_or_order",
            ),
        ),
    ]
