# Generated by Django 5.0.6 on 2026-09-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0004_remove_bookingpaymentsplit_unique_active_split_per_booking_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payer",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
